# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
