# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190224_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile')),
            ],
        ),
    ]
