# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190224_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecontact',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
