# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_degree', models.CharField(choices=[('High School', 'HIGH SCHOOL'), ('undergrad', 'UNDERGRAD'), ('postgrad', 'POSTGRAD')], max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.DateField()),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('cert_image', models.FileField(blank=True, upload_to='cert_images/')),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Bio')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Bio')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.DateField()),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('organisation', models.CharField(blank=True, max_length=128)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Bio')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(blank=True, max_length=128, null=True)),
                ('designation', models.CharField(blank=True, max_length=128, null=True)),
                ('worked_from', models.DateTimeField()),
                ('worked_till', models.DateTimeField()),
                ('current', models.BooleanField(default=False)),
                ('describe', models.TextField(blank=True)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Bio')),
            ],
        ),
    ]
