# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='worked_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='worked_till',
            field=models.DateField(),
        ),
    ]
