# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190421_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='education_from',
            field=models.DateField(default='1990-01-01'),
        ),
    ]
